/* AUTH */
export const AUTH = 'AUTH';
/* APP STATE ACTIONS */
export const APPSTATE_SET = 'APPSTATE_SET';
export const APPSTATE_ERROR = 'APPSTATE_ERROR';
/* ERROR */
export const APP_ERROR = 'APP_ERROR';
export const APP_ERROR_CLEAR = 'APP_ERROR_CLEAR';
/* CG */
export const CG_START = 'CG_START';
export const CG_ACTIVE_TASK = 'CG_ACTIVE_TASK';
export const CG_COMPLETE = 'CG_COMPLETE';
export const CG_ERROR = 'CG_ERROR';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
/* NOTES */
export const TOGGLE_NOTE = 'TOGGLE_NOTE';
/* QUESTIONS (Enums)  */
export const SET_QUESTIONS = 'SET_QUESTIONS';
/* QUOTE */
export const GET_QUOTE = 'GET_QUOTE';
/* POLICY */
export const RESET_POLICY = 'RESET_POLICY';
export const GET_POLICY = 'GET_POLICY';
export const SET_POLICY = 'SET_POLICY';
export const SET_SUMMARY_LEDGER = 'SET_SUMMARY_LEDGER';
export const SET_EFFECTIVE_DATE_CHANGE_REASONS = 'SET_EFFECTIVE_DATE_CHANGE_REASONS';
export const SET_PAYMENT_HISTORY = 'SET_PAYMENT_HISTORY';
export const SET_BILLING_OPTIONS = 'SET_BILLING_OPTIONS';
export const SET_ENDORSEMENT_HISTORY = 'SET_ENDORSEMENT_HISTORY';
export const SET_CANCEL_OPTIONS = 'SET_CANCEL_OPTIONS';
export const SET_PAYMENT_OPTIONS = 'SET_PAYMENT_OPTIONS';
/* SEARCH ACTIONS */
export const SEARCH = 'SEARCH';
export const RESET_SEARCH = 'RESET_SEARCH';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
/* TODO: DEPRECATED - SERVICE */
export const SERVICE_REQUEST = 'SERVICE_REQUEST';

/* QUOTE ACTIONS */
export const SET_QUOTE = 'SET_QUOTE';
