/* APP STATE ACTIONS */
export const APPSTATE_SET = 'APPSTATE_SET';
export const APPSTATE_ERROR = 'APPSTATE_ERROR';

/* UI Actions */
export const TOGGLE_NOTE = 'TOGGLE_NOTE';
export const TOGGLE_DIARY = 'TOGGLE_DIARY';
export const TOGGLE_MINIMIZE_DIARY = 'TOGGLE_MINIMIZE_DIARY';
export const TOGGLE_MINIMIZE_NOTE = 'TOGGLE_MINIMIZE_NOTE';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
/* ERROR */
export const APP_ERROR = 'APP_ERROR';
export const APP_ERROR_CLEAR = 'APP_ERROR_CLEAR';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
/* QUESTIONS (Enums)  */
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_ASSIGNEE_OPTIONS = 'SET_ASSIGNEE_OPTIONS';
export const SET_LISTS = 'SET_LISTS';
/* QUOTE */
export const GET_QUOTE = 'GET_QUOTE';
/* POLICY */
export const RESET_POLICY = 'RESET_POLICY';
export const SET_POLICY = 'SET_POLICY';
export const SET_CLAIMS = 'SET_CLAIMS';
export const SET_SUMMARY_LEDGER = 'SET_SUMMARY_LEDGER';
export const SET_EFFECTIVE_DATE_CHANGE_REASONS =
  'SET_EFFECTIVE_DATE_CHANGE_REASONS';
export const SET_PAYMENT_HISTORY = 'SET_PAYMENT_HISTORY';
export const SET_BILLING_OPTIONS = 'SET_BILLING_OPTIONS';
export const SET_ENDORSEMENT_HISTORY = 'SET_ENDORSEMENT_HISTORY';
export const SET_CANCEL_OPTIONS = 'SET_CANCEL_OPTIONS';
export const SET_PAYMENT_OPTIONS = 'SET_PAYMENT_OPTIONS';
export const SET_POLICIES_FOR_AGENCY = 'SET_POLICIES_FOR_AGENCY';
/* NOTES ACTIONS */
export const SET_NOTES = 'SET_NOTES';
export const SET_NOTES_SYNCED = 'SET_NOTES_SYNCED';
/* DIARIES ACTIONS */
export const SET_DIARIES = 'SET_DIARIES';
/* TODO: DEPRECATED - SERVICE */
export const SERVICE_REQUEST = 'SERVICE_REQUEST';

/* QUOTE ACTIONS */
export const SET_QUOTE = 'SET_QUOTE';
export const SET_RETRIEVED_QUOTE = 'SET_RETRIEVED_QUOTE';

/* AGENCY */
export const SET_AGENCIES = 'SET_AGENCIES';
export const SET_AGENCY = 'SET_AGENCY';
export const SET_AGENTS = 'SET_AGENTS';
export const SET_AGENTS_LIST = 'SET_AGENTS_LIST';
export const SET_ORPHANED_AGENTS = 'SET_ORPHANED_AGENTS';
export const SET_AOR_AGENTS = 'SET_AOR_AGENTS';
/* TERRITORY MANAGER */
export const SET_TERRITORY_MANAGERS = 'SET_TERRITORY_MANAGERS';

/* ZIPCODE SETTINGS */
export const SET_ZIPCODE_SETTINGS = 'SET_ZIPCODE_SETTINGS';
