#!/bin/bash

echo REACT_APP_API_URL=$API_URL > .env
echo REACT_APP_AUTH0_PRIMARY_URL=$AUTH0_PRIMARY_URL >> .env
echo REACT_APP_AQA_SSO_URL=$AQA_SSO_URL >> .env
echo REACT_APP_AUTH0_DOMAIN=$AUTH0_DOMAIN >> .env
echo REACT_APP_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID >> .env
echo REACT_APP_AUTH0_CONNECTION=$AUTH0_CONNECTION >> .env
echo REACT_APP_AUTH0_AUDIENCE=$AUTH0_AUDIENCE >> .env
echo CI=true >> .env
